---
title: "JHU_SI Project"
author: "mbh"
date: "Thursday, June 04, 2015"
output: html_document
---


## Rubric

In this project you will investigate the exponential distribution in R and compare it with the Central Limit Theorem. The exponential distribution can be simulated in R with rexp(n, lambda) where lambda is the rate parameter. The mean of 
exponential distribution is 1/lambda and the standard deviation is also 1/lambda.

lambda<-0.2
means<-apply(matrix(rexp(40000,lambda),1000, 40), 1, mean)
hist(means)
mean(means)
sd(means)

Set lambda = 0.2 for all of the simulations. You will investigate the distribution of averages of 40 exponentials. Note that you will need to do a thousand simulations.

Illustrate via simulation and associated explanatory text the properties of the distribution of the mean of 40 exponentials.  You should
1. Show the sample mean and compare it to the theoretical mean of the distribution.
2. Show how variable the sample is (via variance) and compare it to the theoretical variance of the distribution.
3. Show that the distribution is approximately normal.

In point 3, focus on the difference between the distribution of a large collection of random exponentials and the distribution of a large collection of averages of 40 exponentials. 


## Title

(give an appropriate title) and Author Name

## Overview

In a few (2-3) sentences explain what is going to be reported on.

## Simulations

Include English explanations of the simulations you ran, with the accompanying R code. Your explanations should make clear what the R code accomplishes.

## Sample Mean versus Theoretical Mean

Include figures with titles. In the figures, highlight the means you are comparing. Include text that explains the figures and what is shown on them, and provides appropriate numbers.

## Sample Variance versus Theoretical Variance
Include figures (output from R) with titles. Highlight the variances you are comparing. Include text that explains your understanding of the differences of the variances.

##Distribution

Via figures and text, explain how one can tell the distribution is approximately normal.